### ISSUE TITLE
som_show and Matlab R2014b: Cannot convert double value -1 to a handle

### ISSUE THREAD

**Issue by willfurnass** [ilarinieminen/SOM-Toolbox#2]
When trying to run `som_demo2` in Matlab R2014b I get the following:

```matlab
som_show(sMap,'umat','all','empty','Labels')
Cannot convert double value -1 to a handle

Error in som_show (line 496)
    h_colorbar(i,1)=-1;

Error in som_demo2 (line 259)
som_show(sMap,'umat','all','empty','Labels')
````

Can this be fixed by commenting out `h_colorbar(i,1)=-1;` in `som_show.m` or skipping this line `if verLessThan('matlab', '8.4')`?

**Comment by pepimpepa** [comment]
If I comment the line 496 in som_show.m, everything works fine in Matlab R2015a
